import { createContext, useContext, useState, ReactNode } from "react";

type Language = "FR" | "EN" | "AR";

interface LangContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  FR: {
    // Navbar & Footer
    "Accueil": "Accueil",
    "Logements": "Logements",
    "Avis Clients": "Avis Clients",
    "Avis Personnel": "Avis Personnel",
    "Espace Propriétaire": "Espace Propriétaire",
    "Se connecter": "Se connecter",
    "Mode clair": "Mode clair",
    "Mode sombre": "Mode sombre",
    "Votre plateforme de confiance": "Votre plateforme de confiance pour trouver le logement idéal.",
    "Emplois": "Emplois",
    "Partenaires": "Partenaires",
    "Publications": "Publications",
    "FAQ / Support": "FAQ / Support",
    "Sécurité": "Sécurité",
    "Nous contacter": "Nous contacter",
    "Conditions": "Conditions",
    "Confidentialité": "Confidentialité",
    "Cookies": "Cookies",
    "Tous droits réservés": "Tous droits réservés",
    "Tous": "Tous",
    // Index page
    "Trouvez votre logement idéal": "Trouvez votre logement idéal",
    "Les meilleures activités et hébergements": "Les meilleures activités et hébergements présentés sur notre site web",
    "Explorer les logements": "Explorer les logements",
    "Notre communauté en chiffres": "Notre communauté en chiffres",
    "Visiteurs par mois": "Visiteurs par mois",
    "Logements listés": "Logements listés",
    "Clients satisfaits": "Clients satisfaits",
    "Pourquoi choisir notre site ?": "Pourquoi choisir notre site ?",
    "Expérience personnalisée": "Expérience personnalisée",
    "Des recommandations adaptées": "Des recommandations adaptées à vos goûts et besoins",
    "Logements variés": "Logements variés",
    "Hôtels, maisons, fermes": "Hôtels, maisons, fermes, et bien plus encore",
    "Service rapide": "Service rapide",
    "Réservation en quelques clics": "Réservation en quelques clics, réponse immédiate",
    "Données sécurisées": "Données sécurisées",
    "Vos informations sont protégées": "Vos informations sont protégées et confidentielles",
    "Expérience depuis 6 ans": "Expérience depuis 6 ans",
    "Une expertise reconnue": "Une expertise reconnue dans le domaine de l'hébergement",
    "Se connecter pour profiter": "Se connecter pour profiter au maximum de l'expérience",
    "Créez votre compte gratuitement": "Créez votre compte gratuitement et accédez à des fonctionnalités exclusives",
    "Commencer maintenant": "Commencer maintenant",
    // Hotels page
    "Trier par": "Trier par",
    "Catégorie": "Catégorie",
    "Événements": "Événements",
    "Saison": "Saison",
    "Attractions": "Attractions",
    "Catégories": "Catégories",
    "Événements à proximité": "Événements à proximité",
    "Saisons": "Saisons",
    "Attractions à proximité": "Attractions à proximité",
    "Culturel": "Culturel",
    "Sportif": "Sportif",
    "Sélectionnez un événement": "Sélectionnez un événement",
    "Sélectionnez une saison": "Sélectionnez une saison",
    "Sélectionnez une attraction": "Sélectionnez une attraction",
    "Nom": "Nom",
    "Gouvernorat": "Gouvernorat",
    "Catégorie_col": "Catégorie",
    "Propriétaire": "Propriétaire",
    "Adresse (coordonnées)": "Adresse (coordonnées)",
    "Calendrier": "Calendrier",
    "Événements (dist.)": "Événements (dist.)",
    "Saison_col": "Saison",
    "Attractions (dist.)": "Attractions (dist.)",
    "Nb. Avis": "Nb. Avis",
    "Avis_col": "Avis",
    "Recommander": "Recommander",
    "dates": "dates",
    "Logement disponible": "Logement disponible",
    "Événement à proximité": "Événement à proximité",
    "Voir les avis": "Voir les avis",
    "Description": "Description",
    "Pourquoi choisir ce logement": "Pourquoi choisir ce logement ?",
    "Recommander pour": "Recommander pour",
    "Partagez vos recommandations": "Partagez vos recommandations d'attractions et événements à proximité de ce logement.",
    "Attraction recommandée": "Attraction recommandée :",
    "Nom de l'attraction": "Nom de l'attraction...",
    "Événement recommandé": "Événement recommandé :",
    "Nom de l'événement": "Nom de l'événement...",
    "Détails": "Détails :",
    "Pourquoi recommandez-vous": "Pourquoi recommandez-vous cet endroit/événement...",
    "Enregistrer la recommandation": "Enregistrer la recommandation",
    "Merci ! Votre recommandation": "Merci ! Votre recommandation a été enregistrée.",
    "Lieu": "Lieu :",
    "Adresse": "Adresse :",
    "Date": "Date :",
    "Horaires": "Horaires :",
    "Prix": "Prix :",
    "Rechercher": "Rechercher...",
    "Aucun logement trouvé": "Aucun logement trouvé pour ce filtre.",
    "Tous les logements": "Tous les logements (A-Z)",
    "Liste des": "Liste des",
    "Logements près": "Logements près :",
    "Hôtel": "Hôtel",
    "Maison": "Maison",
    "Maison d'hôtes": "Maison d'hôtes",
    "Ferme": "Ferme",
    // Avis page
    "Les avis des clients": "Les avis des clients",
    "Découvrez ce que nos visiteurs pensent": "Découvrez ce que nos visiteurs pensent",
    "obtenu": "obtenu",
    "Veuillez entrer votre avis": "Veuillez entrer votre avis",
    "Sélectionnez le logement": "Sélectionnez le logement ou l'événement sur lequel vous voulez donner votre avis",
    "Accéder à mon historique": "Accéder à mon historique de réservations",
    // Avis Personnel page
    "Mon espace avis": "Mon espace avis — Historique",
    "Veuillez répondre avec toute transparence": "Veuillez répondre avec toute transparence.",
    "Envoyé": "Envoyé",
    "En attente": "En attente",
    "Sélectionnez l'événement": "Sélectionnez l'événement sur lequel vous voulez donner votre avis",
    "Questionnaire d'évaluation": "Questionnaire d'évaluation",
    "Tous les champs sont obligatoires": "Tous les champs sont obligatoires sauf mention contraire",
    "Votre séjour est terminé": "Votre séjour est terminé. Vous pouvez uniquement visualiser ce formulaire mais vous ne pouvez plus le modifier.",
    "Oui": "Oui",
    "Non": "Non",
    "Si non, voici la carte": "Si non, voici la carte — vous pourrez préciser l'emplacement exact.",
    "Si vous avez pris des photos": "Si vous avez pris des photos :",
    "Télécharger des photos": "Télécharger des photos",
    "Vous pouvez vous exprimer": "Vous pouvez vous exprimer librement :",
    "Partagez votre expérience": "Partagez votre expérience...",
    "Votre localisation...": "Votre localisation...",
    "Vos suggestions...": "Vos suggestions...",
    "Ajouter une recommandation": "Ajouter une recommandation (attractions/événements à proximité)",
    "Masquer": "Masquer",
    "Note attribuée automatiquement": "Note attribuée automatiquement",
    "En remplissant ce formulaire": "En remplissant ce formulaire, vous pouvez profiter de",
    "de réduction sur votre prochaine réservation": "de réduction sur votre prochaine réservation !",
    "Note du site": "Note du site",
    "Valider le formulaire": "Valider le formulaire",
    "Formulaire verrouillé": "Formulaire verrouillé",
    "Merci beaucoup": "Merci beaucoup !",
    "Votre avis a été enregistré": "Votre avis a été enregistré avec succès.",
    "Vos récompenses": "Vos récompenses",
    "Note obtenue": "Note obtenue",
    "Réduction obtenue": "Réduction obtenue",
    "Votre réduction de": "Votre réduction de",
    "sera appliquée automatiquement": "sera appliquée automatiquement sur votre prochaine réservation.",
    "Commentaire": "Commentaire : +3 pts | 📸 Photos : +1 pt/photo (max 3)",
    "Note calculation": "≥18/20 → 15% | ≥14/20 → 10% | ≥10/20 → 5% | <10/20 → 2%",
    "Retour à l'historique": "Retour à l'historique",
    // New questionnaire
    "Comment évaluez-vous votre expérience globale": "Comment évaluez-vous votre expérience globale ?",
    "La localisation du logement était-elle correctement indiquée": "La localisation du logement était-elle correctement indiquée ?",
    "Si non, veuillez préciser la localisation correcte": "Si non, veuillez préciser la localisation correcte (facultatif) :",
    "Avez-vous assisté à des événements ou visité des attractions durant votre séjour": "Avez-vous assisté à des événements ou visité des attractions durant votre séjour ?",
    "Avez-vous assisté à des événements durant votre séjour": "Avez-vous assisté à des événements durant votre séjour ?",
    "Comment évaluez-vous la qualité des événements": "Quelle est votre évaluation de la qualité des événements auxquels vous avez assisté ?",
    "Avez-vous visité des attractions durant votre séjour": "Avez-vous visité des attractions durant votre séjour ?",
    "Comment évaluez-vous la qualité des attractions": "Quelle est votre évaluation de la qualité des attractions visitées ?",
    "Comment évaluez-vous la qualité des événements et/ou attractions": "Comment évaluez-vous la qualité des événements et/ou attractions ?",
    "Commentaires (facultatif)": "Commentaires (facultatif) :",
    "Recommanderiez-vous ce logement": "Recommanderiez-vous ce logement ?",
    "Suggestions d'amélioration ou recommandations (facultatif)": "Suggestions d'amélioration ou recommandations (facultatif) :",
    "Excellente": "Excellente",
    "Très satisfaisante": "Très satisfaisante",
    "Satisfaisante": "Satisfaisante",
    "Moyenne": "Moyenne",
    "Insatisfaisante": "Insatisfaisante",
    "Le logement était-il conforme à vos attentes": "Le logement était-il conforme à vos attentes ?",
    "Le logement correspondait-il à la description fournie": "Le logement correspondait-il à la description fournie ?",
    "Le logement était-il propre": "Le logement était-il propre ?",
    "Le logement était-il sécurisé": "Le logement était-il sécurisé ?",
    "La localisation était-elle correctement indiquée": "La localisation était-elle correctement indiquée ?",
    "Comment évaluez-vous le comportement du propriétaire": "Comment évaluez-vous le comportement du propriétaire ?",
    "Excellent": "Excellent",
    "Bon": "Bon",
    "Moyen": "Moyen",
    "Insatisfaisant": "Insatisfaisant",
    "Avez-vous rencontré un problème": "Avez-vous rencontré un problème ou un incident durant votre séjour ?",
    "Si oui, veuillez préciser": "Si oui, veuillez préciser :",
    "Si oui, veuillez préciser (facultatif)": "Si oui, veuillez préciser (facultatif) :",
    "Si oui, précisez (facultatif)": "Si oui, précisez (facultatif) :",
    "Y a-t-il eu des éléments qui vous ont dérangé": "Y a-t-il eu des éléments qui vous ont dérangé ?",
    "Si oui, précisez": "Si oui, veuillez préciser :",
    "Avez-vous pris des photos du logement": "Avez-vous pris des photos du logement ?",
    // Proprietaire page
    "Bienvenue": "Bienvenue ! Gardez votre mise à jour",
    "Photos / Vidéos du logement": "Photos / Vidéos du logement",
    "Télécharger": "Télécharger",
    "Annonces des événements": "Annonces des événements",
    "Soirées, productions": "Soirées, productions, films, foires, jours nouveaux...",
    "Ajouter": "Ajouter",
    "Promotions": "Promotions",
    "Pourcentage de réduction": "Pourcentage de réduction",
    "Date de début": "Date de début",
    "Date de fin": "Date de fin",
    "Personnalités visitées": "Personnalités visitées",
    "Rénovations": "Rénovations",
    "Enregistrer": "Enregistrer",
    "Titre de l'événement": "Titre de l'événement",
    "Date (JJ/MM/AAAA)": "Date (JJ/MM/AAAA)",
    "Promotions lors des basses saisons": "Promotions lors des basses saisons",
    "Pourcentage": "Pourcentage (%)",
    "Du": "Du",
    "Jusqu'à": "Jusqu'à",
    "Personnes célèbres": "Personnes célèbres qui l'ont visité",
    "Noms séparés par des virgules": "Noms séparés par des virgules",
    "Rénovations récentes": "Rénovations récentes",
    "Décrivez les rénovations": "Décrivez les rénovations récentes...",
    "Mettre à jour": "Mettre à jour",
    // Connexion page
    "Se connecter_title": "Se connecter",
    "Accédez à votre espace personnel": "Accédez à votre espace personnel",
    "Nom complet": "Nom complet",
    "Votre nom complet": "Votre nom complet",
    "Mot de passe": "Mot de passe",
    "Email": "Email",
    "Email ou mot de passe incorrect": "Email ou mot de passe incorrect",
    "Connexion en cours...": "Connexion en cours...",
    "Pas de compte?": "Pas de compte?",
    "S'inscrire": "S'inscrire",
    "Compte démo": "Compte démo",
    "Client": "Client",
    "Déconnexion": "Déconnexion",
    // Additional
    "Historique des réservations": "Historique des réservations",
    "Nom du logement": "Nom du logement",
    "Durée": "Durée",
    "Date début": "Date début",
    "Dates (début - fin)": "Dates (début - fin)",
    "Avis envoyé": "Avis envoyé",
    "Action": "Action",
    "Donner mon avis": "Donner mon avis",
    "Avis sur un logement": "Avis sur un logement",
  },
  EN: {
    "Accueil": "Home",
    "Logements": "Accommodations",
    "Avis Clients": "Client Reviews",
    "Avis Personnel": "Personal Reviews",
    "Espace Propriétaire": "Owner Space",
    "Se connecter": "Login",
    "Mode clair": "Light mode",
    "Mode sombre": "Dark mode",
    "Votre plateforme de confiance": "Your trusted platform to find the ideal accommodation.",
    "Emplois": "Jobs",
    "Partenaires": "Partners",
    "Publications": "Publications",
    "FAQ / Support": "FAQ / Support",
    "Sécurité": "Security",
    "Nous contacter": "Contact us",
    "Conditions": "Terms",
    "Confidentialité": "Privacy",
    "Cookies": "Cookies",
    "Tous droits réservés": "All rights reserved",
    "Tous": "All",
    "3 nuits": "3 nights",
    "5 nuits": "5 nights",
    "2 nuits": "2 nights",
    "Trouvez votre logement idéal": "Find your ideal accommodation",
    "Les meilleures activités et hébergements": "The best activities and accommodations presented on our website",
    "Explorer les logements": "Explore accommodations",
    "Notre communauté en chiffres": "Our community in numbers",
    "Visiteurs par mois": "Visitors per month",
    "Logements listés": "Listed accommodations",
    "Clients satisfaits": "Satisfied customers",
    "Pourquoi choisir notre site ?": "Why choose our site?",
    "Expérience personnalisée": "Personalized experience",
    "Des recommandations adaptées": "Recommendations tailored to your tastes and needs",
    "Logements variés": "Varied accommodations",
    "Hôtel, maisons, fermes": "Hotels, houses, farms, and much more",
    "Service rapide": "Fast service",
    "Réservation en quelques clics": "Booking in a few clicks, immediate response",
    "Données sécurisées": "Secured data",
    "Vos informations sont protégées": "Your information is protected and confidential",
    "Expérience depuis 6 ans": "6 years of experience",
    "Une expertise reconnue": "Recognized expertise in accommodation",
    "Se connecter pour profiter": "Connect to get the most out of the experience",
    "Créez votre compte gratuitement": "Create your account for free and access exclusive features",
    "Commencer maintenant": "Get started",
    "Trier par": "Sort by",
    "Catégorie": "Category",
    "Événements": "Events",
    "Saison": "Season",
    "Attractions": "Attractions",
    "Catégories": "Categories",
    "Événements à proximité": "Nearby events",
    "Saisons": "Seasons",
    "Attractions à proximité": "Nearby attractions",
    "Culturel": "Cultural",
    "Sportif": "Sports",
    "Hôtel": "Hotel",
    "Maison": "House",
    "Maison d'hôtes": "Guesthouse",
    "Ferme": "Farm",
    "Printemps": "Spring",
    "Été": "Summer",
    "Automne": "Autumn",
    "Hiver": "Winter",
    "Festival de Carthage": "Carthage Festival",
    "Festival de Dougga": "Dougga Festival",
    "Festival de Hammamet": "Hammamet Festival",
    "Journées Cinématographiques": "Film Days",
    "Football": "Football",
    "Basketball": "Basketball",
    "Tennis": "Tennis",
    "Handball": "Handball",
    "Stade Olympique de Radès": "Radès Olympic Stadium",
    "Salle omnisports de Sousse": "Sousse Sports Hall",
    "Terrain de tennis": "Tennis Court",
    "Terrain de handball": "Handball Court",
    "Palais des Congrès": "Congress Palace",
    "Salle des fêtes": "Event Hall",
    "Foire Internationale de Tunis": "Tunis International Fair",
    "Centre commercial Tunisia Mall": "Tunisia Mall",
    "Parc du Belvédère": "Belvédère Park",
    "Parc Carthage Land": "Carthage Land",
    "Zoo de Tunis": "Tunis Zoo",
    "Musée du Bardo": "Bardo Museum",
    "Site archéologique": "Archaeological Site",
    "Hôtel El Mouradi Hammamet": "El Mouradi Hammamet Hotel",
    "Hôtel Laico Tunis": "Laico Tunis Hotel",
    "Hôtel Sheraton Sousse": "Sheraton Sousse Hotel",
    "Maison Sidi Bou Saïd": "Sidi Bou Saïd House",
    "Résidence Marina Yasmine": "Marina Yasmine Residence",
    "Villa Djerba Heritage": "Djerba Heritage Villa",
    "Dar El Jeld": "Dar El Jeld House",
    "Dar Zaghouan": "Zaghouan House",
    "Dar Essalem Tozeur": "Essalem Tozeur House",
    "Ferme Bio Testour": "Testour Bio Farm",
    "Ferme Oléicole Sfax": "Sfax Olive Farm",
    "Domaine Viticole Grombalia": "Grombalia Wine Estate",
    "Ahmed Ben Salah": "Ahmed Ben Salah",
    "Fatima Trabelsi": "Fatima Trabelsi",
    "Karim Gharbi": "Karim Gharbi",
    "Nadia Bouzid": "Nadia Bouzid",
    "Youssef Hammami": "Youssef Hammami",
    "Samira Jlassi": "Samira Jlassi",
    "Hassan Meddeb": "Hassan Meddeb",
    "Amina Cherif": "Amina Cherif",
    "Mohamed Chaabane": "Mohamed Chaabane",
    "Ali Ben Ali": "Ali Ben Ali",
    "Slaheddine Mansour": "Slaheddine Mansour",
    "Habib Zouhair": "Habib Zouhair",
    "Sélectionnez un événement": "Select an event",
    "Sélectionnez une saison": "Select a season",
    "Sélectionnez une attraction": "Select an attraction",
    "Nom": "Name",
    "Gouvernorat": "Governorate",
    "Catégorie_col": "Category",
    "Propriétaire": "Owner",
    "Adresse (coordonnées)": "Address (coordinates)",
    "Calendrier": "Calendar",
    "Événements (dist.)": "Events (dist.)",
    "Saison_col": "Season",
    "Attractions (dist.)": "Attractions (dist.)",
    "Nb. Avis": "Rev. #",
    "Avis_col": "Reviews",
    "Recommander": "Recommend",
    "dates": "dates",
    "Logement disponible": "Accommodation available",
    "Événement à proximité": "Event nearby",
    "Voir les avis": "View reviews",
    "Description": "Description",
    "Pourquoi choisir ce logement": "Why choose this accommodation?",
    "Recommander pour": "Recommend for",
    "Partagez vos recommandations": "Share your recommendations for attractions and events near this accommodation.",
    "Attraction recommandée": "Recommended attraction:",
    "Nom de l'attraction": "Name of attraction...",
    "Événement recommandé": "Recommended event:",
    "Nom de l'événement": "Name of event...",
    "Détails": "Details:",
    "Pourquoi recommandez-vous": "Why do you recommend this place/event...",
    "Enregistrer la recommandation": "Save recommendation",
    "Merci ! Votre recommandation": "Thank you! Your recommendation has been saved.",
    "Lieu": "Location:",
    "Adresse": "Address:",
    "Date": "Date:",
    "Horaires": "Hours:",
    "Prix": "Price:",
    "Rechercher": "Search...",
    "Aucun logement trouvé": "No accommodation found for this filter.",
    "Tous les logements": "All accommodations (A-Z)",
    "Liste des": "List of",
    "Logements près": "Accommodations near:",
    "Les avis des clients": "Client Reviews",
    "Découvrez ce que nos visiteurs pensent": "Discover what our visitors think",
    "obtenu": "obtained",
    "Veuillez entrer votre avis": "Please enter your review",
    "Sélectionnez le logement": "Select the accommodation or event you want to review",
    "Accéder à mon historique": "Access my booking history",
    "Mon espace avis": "My reviews - History",
    "Veuillez répondre avec toute transparence": "Please answer with complete transparency.",
    "Envoyé": "Sent",
    "En attente": "Pending",
    "Sélectionnez l'événement": "Select the event you want to review",
    "Questionnaire d'évaluation": "Evaluation questionnaire",
    "Tous les champs sont obligatoires": "All fields are required",
    "Votre séjour est terminé": "Your stay is over. You can only view this form but can no longer edit it.",
    "Oui": "Yes",
    "Non": "No",
    "Si non, voici la carte": "If no, here's the map - you can specify the exact location.",
    "Si vous avez pris des photos": "If you took photos:",
    "Télécharger des photos": "Download photos",
    "Vous pouvez vous exprimer": "You can express yourself freely:",
    "Partagez votre expérience": "Share your experience...",
    "Votre localisation...": "Your location...",
    "Vos suggestions...": "Your suggestions...",
    "Décrivez le problème...": "Describe the problem...",
    "Décrivez ce qui vous a gêné...": "Describe what bothered you...",
    "Ajouter une recommandation": "Add a recommendation (attractions/events nearby)",
    "Masquer": "Hide",
    "Note attribuée automatiquement": "Automatically assigned rating",
    "En remplissant ce formulaire": "By filling this form, you can enjoy",
    "de réduction sur votre prochaine réservation": "% discount on your next booking!",
    "Note du site": "Site rating",
    "Valider le formulaire": "Submit form",
    "Formulaire verrouillé": "Form locked",
    "Merci beaucoup !": "Thank you very much!",
    "Votre avis a été enregistré": "Your review has been recorded successfully.",
    "Vos récompenses": "Your rewards",
    "Note obtained": "Rating obtained",
    "Réduction obtained": "Discount obtained",
    "Votre réduction de": "Your discount of",
    "sera appliquée automatiquement": "will be automatically applied to your next booking.",
    "Commentaire": "Comment: +3 pts | 📸 Photos: +1 pt/photo (max 3)",
    "Note calculation": "≥18/20 → 15% | ≥14/20 → 10% | ≥10/20 → 5% | <10/20 → 2%",
    "Retour à l'historique": "Back to history",
    // New questionnaire
    "Comment évaluez-vous votre expérience globale": "How do you rate your overall experience?",
    "Très satisfaisante": "Very satisfactory",
    "Satisfaisante": "Satisfactory",
    "Moyenne": "Average",
    "Insatisfaisante": "Unsatisfactory",
    "Le logement était-il conforme à vos attentes": "Did the lodging meet your expectations?",
    "Le logement correspondait-il à la description fournie": "Did the lodging match the description provided?",
    "Le logement était-il propre": "Was the lodging clean?",
    "Le logement était-il sécurisé": "Was the lodging secure?",
    "La localisation était-elle correctement indiquée": "Was the location correctly indicated?",
    "Comment évaluez-vous le comportement du propriétaire": "How do you rate the owner's behavior?",
    "Excellent": "Excellent",
    "Bon": "Good",
    "Moyen": "Average",
    "Insatisfaisant": "Unsatisfactory",
    "Avez-vous rencontré un problème": "Did you encounter a problem or incident during your stay?",
    "Si oui, veuillez préciser": "If yes, please specify:",
    "Si oui, veuillez préciser (facultatif)": "If yes, please specify (optional):",
    "Y a-t-il eu des éléments qui vous ont dérangé": "Were there any elements that bothered you?",
    "Si oui, précisez": "If yes, please specify:",
    "Si oui, précisez (facultatif)": "If yes, please specify (optional):",
    "Avez-vous pris des photos du logement": "Did you take photos of the lodging?",
    "La localisation du logement était-elle correctement указана": "Was the location of the lodging correctly indicated?",
    "Si non, veuillez préciser la localisation correcte": "If no, please specify the correct location (optional):",
    "Avez-vous assisté à des événements ou visité des attractions durant votre séjour": "Did you attend events or visit attractions during your stay?",
    "Avez-vous assisté à des événements durant votre séjour": "Did you attend events during your stay?",
    "Comment évaluez-vous la qualité des événements": "How would you rate the quality of the events you attended?",
    "Avez-vous visité des attractions durant votre séjour": "Did you visit attractions during your stay?",
    "Comment évaluez-vous la qualité des attractions": "How would you rate the quality of the attractions you visited?",
    "Comment évaluez-vous la qualité des événements et/ou attractions": "How do you rate the quality of events and/or attractions?",
    "Excellente": "Excellent",
    "Bonne": "Good",
    "Commentaires (facultatif)": "Comments (optional):",
    "Recommanderiez-vous ce logement": "Would you recommend this lodging?",
    "Suggestions d'amélioration ou recommandations (facultatif)": "Improvement suggestions or recommendations (optional):",
    // Questions
    "L'expérience était bonne": "Was the experience good?",
    "Le logement était bon": "Was the lodging good?",
    "S'il y a eu un événement": "Was there an event?",
    "Le logement respecte la description": "Does the lodging match the description?",
    "Le comportement du propriétaire": "Was the owner's behavior good?",
    "La localisation était précisée": "Was the location specified?",
    "C'était bien sécurisé": "Was it well secured?",
    "C'était propre": "Was it clean?",
    "Quelque chose vous a dérangé": "Did something disturb you?",
    "Bienvenue": "Welcome! Keep your accommodation updated",
    "Photos / Vidéos du logement": "Photos / Videos of the lodging",
    "Télécharger": "Download",
    "Annonces des événements": "Event announcements",
    "Soirées, productions": "Evenings, productions, films, fairs, new days...",
    "Ajouter": "Add",
    "Promotions": "Promotions",
    "Pourcentage de réduction": "Discount percentage",
    "Date de début": "Start date",
    "Date de fin": "End date",
    "Personnalités visitées": "Visited personalities",
    "Rénovations": "Renovations",
    "Enregistrer": "Save",
    "Titre de l'événement": "Event title",
    "Date (JJ/MM/AAAA)": "Date (DD/MM/YYYY)",
    "Promotions lors des basses saisons": "Promotions during low seasons",
    "Pourcentage": "Percentage (%)",
    "Du": "From",
    "Jusqu'à": "Until",
    "Personnes célèbres": "Famous people who visited",
    "Noms séparés par des virgules": "Names separated by commas",
    "Rénovations récentes": "Recent renovations",
    "Décrivez les rénovations": "Describe recent renovations...",
    "Mettre à jour": "Update",
    "Se connecter_title": "Login",
    "Accédez à votre espace personnel": "Access your personal space",
    "Nom complet": "Full name",
    "Votre nom complet": "Your full name",
    "Mot de passe": "Password",
    "Email": "Email",
    "Email ou mot de passe incorrect": "Email or password incorrect",
    "Connexion en cours...": "Logging in...",
    "Pas de compte?": "No account?",
    "S'inscrire": "Sign up",
    "Compte démo": "Demo account",
    "Client": "Client",
    "Déconnexion": "Logout",
    "Historique des réservations": "Booking History",
    "Nom du logement": "Accommodation name",
    "Durée": "Duration",
    "Date début": "Start date",
    "Dates (début - fin)": "Dates (start - end)",
    "Avis envoyé": "Review sent",
    "Action": "Action",
    "Donner mon avis": "Give my review",
    "Avis sur un logement": "Review about accommodation",
  },
  AR: {
    "Accueil": "الرئيسية",
    "Logements": "الإقامة",
    "Avis Clients": "آراء العملاء",
    "Avis Personnel": "آراء شخصية",
    "Espace Propriétaire": "مساحة المالك",
    "Se connecter": "تسجيل الدخول",
    "Mode clair": "الوضع الفاتح",
    "Mode sombre": "الوضع الداكن",
    "Votre plateforme de confiance": "منصتك الموثوقة للعثور على الإقامة المثالية.",
    "Emplois": "وظائف",
    "Partenaires": "شركاء",
    "Publications": "منشورات",
    "FAQ / Support": "الأسئلة الشائعة / الدعم",
    "Sécurité": "الأمان",
    "Nous contacter": "اتصل بنا",
    "Conditions": "الشروط",
    "Confidentialité": "الخصوصية",
    "Cookies": "ملفات تعريف الارتباط",
    "Tous droits réservés": "جميع الحقوق محفوظة",
    "3 nuits": "3 ليالي",
    "5 nuits": "5 ليالي",
    "2 nuits": "2 ليلة",
    "Trouvez votre logement ideal": "اعثر على إقامتك المثالية",
    "Les meilleures activités et hébergements": "أفضل الأنشطة والإقامات معروضة على موقعنا",
    "Explorer les logements": "استكشف الإقامات",
    "Notre communauté en chiffres": "مجتمعنا بالأرقام",
    "Visiteurs par mois": "زوار شهرياً",
    "Logements listés": "إقامات مدرجة",
    "Clients satisfaits": "عملاء راضون",
    "Pourquoi choisir notre site ?": "لماذا تختار موقعنا؟",
    "Expérience personnalisée": "تجربة شخصية",
    "Des recommandations adaptées": "توصيات تناسب أذواقك واحتياجاتك",
    "Logements variés": "إقامات متنوعة",
    "Hôtel, maisons, fermes": "فنادق، بيوت، مزارع، والمزيد",
    "Service rapide": "خدمة سريعة",
    "Réservation en quelques clics": "الحجز بضع نقرات، استجابة فورية",
    "Données sécurisées": "بيانات مؤمنة",
    "Vos informations sont protégées": "معلوماتك محمية وسرية",
    "Expérience depuis 6 ans": "خبرة منذ 6 سنوات",
    "Une expertise reconnue": "خبرة معترف بها في مجال الإقامة",
    "Se connecter pour profiter": "سجل الدخول للاستفادة الكاملة من التجربة",
    "Créez votre compte gratuitement": "أنشئ حسابك مجاناً ووصل إلى ميزات حصرية",
    "Commencer maintenant": "ابدأ الآن",
    "Trier par": "ترتيب حسب",
    "Catégorie": "الفئة",
    "Événements": "الفعاليات",
    "Saison": "الموسم",
    "Attractions": "المعالم",
    "Catégories": "الفئات",
    "Événements à proximité": "فعاليات قريبة",
    "Saisons": "المواسم",
    "Attractions à proximité": "معالم قريبة",
    "Culturel": "ثقافي",
    "Sportif": "رياضي",
    "Hôtel": "فندق",
    "Maison": "بيت",
    "Maison d'hôtes": "دار ضيافة",
    "Ferme": "مزرعة",
    "Printemps": "ربيع",
    "Été": "صيف",
    "Automne": "خريف",
    "Hiver": "شتاء",
    "Festival de Carthage": "مهرجان قرطاج",
    "Festival de Dougga": "مهرجان دققة",
    "Festival de Hammamet": "مFestival de Hammamet",
    "Journées Cinématographiques": "الأيام السينمائية",
    "Football": "كرة القدم",
    "Basketball": "كرة السلة",
    "Tennis": "التنس",
    "Handball": "كرة اليد",
    "Stade Olympique de Radès": "ملعب رادس الأولمبي",
    "Salle omnisports de Sousse": "قاعة الرياضية بسوسة",
    "Terrain de tennis": "ملعب теннис",
    "Terrain de handball": "ملعب كرة اليد",
    "Palais des Congrès": "قصر المؤتمرات",
    "Salle des fêtes": "قاعة الأعراس",
    "Foire Internationale de Tunis": "المعرض الدولي بتونس",
    "Centre commercial Tunisia Mall": "تونيسيا مول",
    "Parc du Belvédère": "حديقة بلفيدير",
    "Parc Carthage Land": "مكارث لاند",
    "Zoo de Tunis": "حديقة حيوانات تونس",
    "Musée du Bardo": "متحف باردو",
    "Site archéologique": "موقع أثري",
    "Hôtel El Mouradi Hammamet": "فندق المرادي Hammamet",
    "Hôtel Laico Tunis": "فندق لايكو تونس",
    "Hôtel Sheraton Sousse": "فندق شيراتون سوسة",
    "Maison Sidi Bou Saïd": "بيت سيدي بو سعيد",
    "Résidence Marina Yasmine": "مارينا ياسمينة",
    "Villa Djerba Heritage": "فيلا جربة هيريتاج",
    "Dar El Jeld": "دار الجلد",
    "Dar Zaghouan": "دار Zaghouan",
    "Dar Essalem Tozeur": "دار السلام",
    "Ferme Bio Testour": "مزرعة بيولوجية تستور",
    "Ferme Oléicole Sfax": "مزرعة زيتون صفاقس",
    "Domaine Viticole Grombalia": "م Domaine",
    "Ahmed Ben Salah": "أحمد بن صالح",
    "Fatima Trabelsi": "فاطمة ترابليسي",
    "Karim Gharbi": "كريم الغريبي",
    "Nadia Bouzid": "نادية بوزيد",
    "Youssef Hammami": "يوسف حمامي",
    "Samira Jlassi": "سميرة جلاسي",
    "Hassan Meddeb": "حسنمدب",
    "Amina Cherif": "أمينة صغير",
    "Mohamed Chaabane": "محمد شعبان",
    "Ali Ben Ali": "علي بن علي",
    "Slaheddine Mansour": "صلاح الدين منصور",
    "Habib Zouhair": "حبيب زوير",
    "Sélectionnez un événement": "اختر فعالية",
    "Sélectionnez une saison": "اختر موسماً",
    "Sélectionnez une attraction": "اختر معلماً",
    "Nom": "الاسم",
    "Gouvernorat": "ولاية",
    "Catégorie_col": "الفئة",
    "Propriétaire": "المالك",
    "Adresse (coordonnées)": "العنوان (الإحداثيات)",
    "Calendrier": "التقويم",
    "Événements (dist.)": "الفعاليات (المسافة)",
    "Saison_col": "الموسم",
    "Attractions (dist.)": "المعالم (المسافة)",
    "Nb. Avis": "عدد الآراء",
    "Avis_col": "الآراء",
    "Recommander": "توصية",
    "dates": "تواريخ",
    "Logement disponible": "إقامة متاحة",
    "Événement à proximité": "فعالية قريبة",
    "Voir les avis": "شاهد الآراء",
    "Description": "الوصف",
    "Pourquoi choisir ce logement": "لماذا تختار هذه الإقامة؟",
    "Recommander pour": "توصية لـ",
    "Partagez vos recommandations": "شارك توصياتك عن المعالم والفعاليات القريبة من هذه الإقامة.",
    "Attraction recommandée": "معلم موصى به:",
    "Nom de l'attraction": "اسم المعلم...",
    "Événement recommandé": "فعالية موصى بها:",
    "Nom de l'événement": "اسم الفعالية...",
    "Détails": "التفاصيل:",
    "Pourquoi recommandez-vous": "لماذا توصي بهذا المكان/الفعالية...",
    "Enregistrer la recommandation": "حفظ التوصية",
    "Merci ! Votre recommandation": "شكراً! تم حفظ توصيتك.",
    "Lieu": "المكان:",
    "Adresse": "العنوان:",
    "Date": "التاريخ:",
    "Horaires": "الساعات:",
    "Prix": "السعر:",
    "Rechercher": "بحث...",
    "Aucun logement trouvé": "لم يتم العثور على إقامة لهذا الفلتر.",
    "Tous les logements": "جميع الإقامات (أ-ي)",
    "Liste des": "قائمة",
    "Logements près": "إقامات قرب:",
    "Les avis des clients": "آراء العملاء",
    "Découvrez ce que nos visiteurs pensent": "اكتشف ما يفكر به زوارنا",
    "obtenu": "تم الحصول عليه",
    "Veuillez entrer votre avis": "يرجى إدخال تقييمك",
    "Sélectionnez le logement": "اختر الإقامة أو الفعالية التي تريد تقييمها",
    "Accéder à mon historique": "الوصول إلى سجل حجوزاتي",
    "Mon espace avis": "مساحة تقييماتي - السجل",
    "Veuillez répondre avec toute transparence": "يرجى الإجابة بشفافية تامة.",
    "Envoyé": "تم الإرسال",
    "En attente": "قيد الانتظار",
    "Sélectionnez l'événement": "اختر الفعالية التي تريد تقييمها",
    "Questionnaire d'évaluation": "استبيان التقييم",
    "Tous les champs sont obligatoires": "جميع الحقول مطلوبة",
    "Votre séjour est terminé": "انتهت إقامتك. يمكنك فقط viewing this form but you can no longer edit it.",
    "Oui": "نعم",
    "Non": "لا",
    "Si non, voici la carte": "إذا لا، ها هي الخريطة - يمكنك تحديد الموقع الدقيق.",
    "Si vous avez pris des photos": "إذا التقطت صوراً:",
    "Télécharger des photos": "تحميل الصور",
    "Vous pouvez vous exprimer": "يمكنك التعبير بحرية:",
    "Partagez votre expérience": "شارك تجربتك...",
    "Votre localisation...": "موقعك...",
    "Vos suggestions...": "اقتراحاتك...",
    "Ajouter une recommandation": "إضافة توصية (معالم/فعاليات قريبة)",
    "Masquer": "إخفاء",
    "Note attribuée automatiquement": "التقييم الممنوح تلقائياً",
    "En remplissant ce formulaire": "By filling this form, you can enjoy",
    "de réduction": "% خصم على حجزك القادم!",
    "Note du site": "تقييم الموقع",
    "Valider le formulaire": "إرسال النموذج",
    "Formulaire verrouillé": "النموذج مقفل",
    "Merci beaucoup": "شكراً جزيلاً!",
    "Votre avis a été enregistré": "تم تسجيل تقييمك بنجاح.",
    "Vos récompenses": "مكافآتك",
    "Note obtained": "التقييم obtained",
    "Réduction obtained": "الخصم obtained",
    "Votre réduction de": "خصمك من",
    "sera appliquée automatiquement": "سيتم تطبيقه تلقائياً على حجزك القادم.",
    "Commentaire": "تعليق: +3 نقاط | 📸 صور: +1 نقطة/صورة (أقصى 3)",
    "Note calculation": "≥18/20 → 15% | ≥14/20 → 10% | ≥10/20 → 5% | <10/20 → 2%",
    "Retour à l'historique": "العودة إلى السجل",
    // New questionnaire
    "Comment évaluez-vous votre expérience globale": "كيف تقييم تجربتك العامة؟",
    "Très satisfaisante": "مرضية جداً",
    "Satisfaisante": "مرضية",
    "Moyenne": "متوسطة",
    "Insatisfaisante": "غير مرضية",
    "Le logement était-il conforme à vos attentes": "هل كان السكن مطابق لتوقعاتك؟",
    "Le logement correspondait-il à la description fournie": "هل كان السكن مطابق للوصف المقدم؟",
    "Le logement était-il propre": "هل كان السكن نظيفاً؟",
    "Le logement était-il sécurisé": "هل كان السكن آمناً؟",
    "La localisation était-elle correctement indiquée": "هل كان الموقع محدد بشكل صحيح؟",
    "Comment évaluez-vous le comportement du propriétaire": "كيف تقيم سلوك المالك؟",
    "Excellent": "ممتاز",
    "Bon": "جيد",
    "Moyen": "متوسط",
    "Insatisfaisant": "غير مرضي",
    "Avez-vous rencontré un problème": "هل واجهت مشكلة أثناء إقامتك؟",
    "Si oui, veuillez préciser": "إذا نعم، يرجى التحديد:",
    "Si oui, veuillez préciser (facultatif)": "إذا نعم، يرجى التحديد (اختياري):",
    "Y a-t-il eu des éléments qui vous ont dérangé": "هل كان هناك عناصر أزعجتك؟",
    "Si oui, précisez": "إذا نعم، يرجى التحديد:",
    "Si oui, précisez (facultatif)": "إذا نعم، يرجى التحديد (اختياري):",
    "Avez-vous pris des photos du logement": "هل التقطت صوراً للسكن؟",
    "La localisation du logement était-elle correctement указана": "هل موقع السكن محدد بشكل صحيح؟",
    "Si non, veuillez préciser la localisation correcte": "يرجى تحديد الموقع الصحيح (اختياري):",
    "Avez-vous assisté à des événements ou.visit... des attractions durant votre séjour": "هل حضرت فعاليات أو زرت معالم أثناء إقامتك؟",
    "Avez-vous assisté à des événements durant votre séjour": "هل حضرت فعاليات أثناء إقامتك؟",
    "Comment évaluez-vous la qualité des événements": "كيف تقيم جودة الفعاليات التي حضرتها؟",
    "Avez-vous visité des attractions durant votre séjour": "هل زرت معالم أثناء إقامتك؟",
    "Comment évaluez-vous la qualité des attractions": "كيف تقيم جودة المعالم التي زرتها؟",
    "Comment évaluez-vous la qualité des événements et/ou attractions": "كيف تقيم جودة الفعاليات و/أو المعالم؟",
    "Excellente": "ممتازة",
    "Bonne": "جيدة",
    "Commentaires (facultatif)": "تعليقات (اختياري):",
    "Recommanderiez-vous ce logement": "هل توصي بهذا السكن؟",
    "Suggestions d'amélioration ou recommandations (facultatif)": "اقتراحات التحسين أو التوصيات (اختياري):",
    "Bienvenue": "مرحباً! حافظ على تحديث إقامتك",
    "Photos / Vidéos du logement": "صور / فيديو الإقامة",
    "Télécharger": "تحميل",
    "Annonces des événements": "إعلانات الأحداث",
    "Soirées, productions": "أمسيات، إنتاجات، أفلام، معارض، أيام جديدة...",
    "Ajouter": "إضافة",
    "Promotions": "العروض الترويجية",
    "Pourcentage de réduction": "نسبة الخصم",
    "Date de début": "تاريخ البدء",
    "Date de fin": "تاريخ النهاية",
    "Personnalités visitées": "الشخصيات الزائرة",
    "Rénovations": "التجديدات",
    "Enregistrer": "حفظ",
    "Titre de l'événement": "عنوان الفعالية",
    "Date (JJ/MM/AAAA)": "التاريخ (يوم/شهر/سنة)",
    "Promotions lors des basses saisons": "العروض الترويجية في المواسم الهادئة",
    "Pourcentage": "النسبة (%)",
    "Du": "من",
    "Jusqu'à": "إلى",
    "Personnes célèbres": "مشاهير زاروه",
    "Noms séparés par des virgules": "أسماء مفصولة بفواصل",
    "Rénovations récentes": "تجديدات حديثة",
    "Décrivez les rénovations": "صف التجديدات الأخيرة...",
    "Mettre à jour": "تحديث",
    "Se connecter_title": "تسجيل الدخول",
    "Accédez à votre espace personnel": "الوصول إلى مساحتك الشخصية",
    "Nom complet": "الاسم الكامل",
    "Votre nom complet": "اسمك الكامل",
    "Mot de passe": "كلمة المرور",
    "Email": "البريد الإلكتروني",
    "Email ou mot de passe incorrect": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    "Connexion en cours...": "جاري تسجيل الدخول...",
    "Pas de compte?": "ليس لديك حساب؟",
    "S'inscrire": "سجل",
    "Compte démo": "حساب تجريبي",
    "Client": "عميل",
    "Déconnexion": "تسجيل الخروج",
    "Historique des réservations": "سجل الحجوزات",
    "Nom du logement": "اسم الإقامة",
    "Durée": "المدة",
    "Date début": "تاريخ البدء",
    "Dates (début - fin)": "التاريخ (البداية - النهاية)",
    "Avis envoyé": "تم إرسال الرأي",
    "Action": "إجراء",
    "Donner mon avis": "أعطِ رأيي",
    "Avis sur un logement": "رأي حول الإقامة",
  },
};

const LangContext = createContext<LangContextType | null>(null);

export const LangProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("FR");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LangContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => {
  const context = useContext(LangContext);
  if (!context) {
    throw new Error("useLang must be used within a LangProvider");
  }
  return context;
};